services:
  db:
    container_name: postgresql
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ducks
      POSTGRES_USER: cage
      POSTGRES_DB: murmur_db

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080